sonar.projectKey=desaprendiendo-playwright-e2e-localfirst
sonar.projectName=desaprendiendo-playwright-e2e-localfirst
sonar.organization=desaprendiendo
sonar.sources=src,web-local,api-local
sonar.tests=tests
sonar.exclusions=node_modules/**,coverage/**,playwright-report/**,test-results/**,web-local-instrumented/**,api-local-instrumented/**
sonar.javascript.lcov.reportPaths=coverage/e2e/lcov.info

sonar.exclusions=\
node_modules/**,\
playwright-report/**,\
test-results/**,\
coverage/**,\
.nyc_output/**,\
dist/**,\
web-local-instrumented/**

sonar.test.inclusions=\
tests/**/*.spec.ts,\
tests/**/*.test.ts

sonar.javascript.lcov.reportPaths=\
coverage/lcov.info,\
coverage/e2e/lcov.info

sonar.sourceEncoding=UTF-8