sonar.projectKey=desaprendiendo-playwright-e2e-localfirst
sonar.projectName=desaprendiendo-playwright-e2e-localfirst
sonar.sources=web-local,api-local
sonar.tests=tests
sonar.exclusions=node_modules/**,coverage/**,playwright-report/**,test-results/**,web-local-instrumented/**,api-local-instrumented/**
sonar.javascript.lcov.reportPaths=coverage/e2e/lcov.info
